### PR TITLE
fix: fix 6 issues 

### LINKED ISSUE #94: 🐛 [Bug]: [tiny-toolkit-pro/ng]: 开启mock模式失败
### Version

v1.0.1

### node-version

v18.4.0

### Link to minimal reproduction

_No response_

### Step to reproduce

``` bash
tiny init pro
```

```
? 确认需要继续执行初始化,请输入(y) y
? 请输入项目名称111： tiny-pro-ng
? 请输入项目描述： 基于TinyPro套件创建的中后台系统
* 请选择您希望使用的客户端技术栈： angular
* 请确保已安装数据库服务（参考文档 https://www.opentiny.design/tiny-cli/docs/toolkits/pro#database）： 暂不配置服务端
```

### What is expected

无报错信息

### What is actually happening

有报错信息
```
2023-09-08 11:40:59 [tiny-toolkit-pro]: 开启mock模式失败
2023-09-08 11:40:59 [tiny-toolkit-pro]: 请手动配置env信息
```

### Any additional comments (optional)

_No response_

### LINKED ISSUE #98: 🐛 [Bug]: [tiny-toolkit-pro] angular项目有对接数据库的选项
根据opentiny文档的描述，仅支持vue对接服务端：https://opentiny.design/tiny-cli/docs/toolkits/pro

### Version

v1.0.1

### node-version

v16.16.0

### Link to minimal reproduction

_No response_

### Step to reproduce

``` bash
tiny init pro
```
```
? 确认需要继续执行初始化,请输入(y) y
? 请输入项目名称： tiny-pro
? 请输入项目描述： 基于TinyPro套件创建的中后台系统
* 请选择您希望使用的客户端技术栈： angular
* 请确保已安装数据库服务（参考文档 https://www.opentiny.design/tiny-cli/docs/toolkits/pro#database）： (Use arrow keys)
> 已完成数据库服务安装，开始配置
  暂不配置服务端
```

### What is expected

没有选择数据库的步骤
```
? 确认需要继续执行初始化,请输入(y) y
? 请输入项目名称： tiny-pro
? 请输入项目描述： 基于TinyPro套件创建的中后台系统
* 请选择您希望使用的客户端技术栈： angular
```
直接创建项目安装

### What is actually happening

可以选择数据库，并且选择后会创建项目失败
```
* 请确保已安装数据库服务（参考文档 https://www.opentiny.design/tiny-cli/docs/toolkits/pro#database）：
已完成数据库服务安装，开始配置
* 请选择数据库类型： mySQL
* 请输入数据库地址： 
* 请输入数据库端口： 
* 请输入数据库名称： 
* 请输入登录用户名： 
* 请输入密码： [hidden]
2023-09-12 18:06:59 [core-fs]: D:\TestSpaces\test\tiny-pro\web\.browserslistrc written successfully
2023-09-12 18:06:59 [core-fs]: D:\TestSpaces\test\tiny-pro\web\.editorconfig written successfully
2023-09-12 18:06:59 [core-fs]: D:\TestSpaces\test\tiny-pro\web\.eslintrc.js written successfully
...
2023-09-12 18:06:59 [core-fs]: D:\TestSpaces\test\tiny-pro\web\tsconfig.app.json written successfully
2023-09-12 18:06:59 [core-fs]: D:\TestSpaces\test\tiny-pro\web\tsconfig.json written successfully
2023-09-12 18:06:59 [core-fs]: D:\TestSpaces\test\tiny-pro\web\tsconfig.spec.json written successfully

2023-09-12 18:06:59 [tiny-toolkit-pro]: 项目模板创建失败
```

### Any additional comments (optional)

_No response_

### LINKED ISSUE #99: 🐛 [Bug]: [tiny-toolkit-pro] vue eggjs项目执行`npm start` 失败
### Version

v1.0.1

### node-version

16.18.0

### Link to minimal reproduction

_No response_

### Step to reproduce

``` shell
tiny init pro
```

```
? 确认需要继续执行初始化,请输入(y) y
? 请输入项目名称： vue-eggjs
? 请输入项目描述： 基于TinyPro套件创建的中后台系统
* 请选择您希望使用的客户端技术栈： vue
* 请选择您希望使用的服务端技术栈： Egg.js
* 请确保已安装数据库服务（参考文档 https://www.opentiny.design/tiny-cli/docs/toolkits/pro#database）：
已完成数据库服务安装，开始配置
* 请选择数据库类型： mySQL
* 请输入数据库地址： 
* 请输入数据库端口： 
* 请输入数据库名称： 
* 请输入登录用户名： 
* 请输入密码： [hidden]
```

``` shell
cd vue-eggjs/eggJs && npm start
```

```
...
node_modules/@types/lodash/common/object.d.ts: 2581: 1 - error
TS1160: Unterminated template literal.

2581

Found 200 errors.
```

### What is expected

eggJs服务端可以运行 `npm start` 命令

### What is actually happening

eggJs服务端运行 `npm start` 报错
```
...
node_modules/@types/lodash/common/object.d.ts: 2581: 1 - error
TS1160: Unterminated template literal.

2581

Found 200 errors.
```

### Any additional comments (optional)

_No response_

### LINKED ISSUE #100: 🐛 [Bug]: [tiny-toolkit] tiny v1.1.0  运行 start时，报错TypeError [ERR_INVALID_ARG_TYPE] 无法启动。
### Version

tiny v1.1.0  @opentiny/tiny-toolkit-dev v1.0.1

### node-version

v20.6.1

### Link to minimal reproduction

**tiny start** 
                                                                                                                                                                                                                                                                                                                                                                                                                                

**/alexblair/windir/www/alexblair_synology_me/test/tinyy/node_modules/.store/append-transform@1.0.0/node_modules/append-transform/index.js:1
TypeError [ERR_INVALID_ARG_TYPE]: The "mod" argument must be an instance of Module. Received an instance of Module
    at new NodeError (node:internal/errors:405:5)**
    at makeRequireFunction (node:internal/modules/helpers:86:11)
    at Module._compile (node:internal/modules/cjs/loader:1231:19)
    at Module.replacementCompile (/alexblair/windir/www/alexblair_synology_me/test/tinyy/node_modules/.store/append-transform@1.0.0/node_modules/append-transform/index.js:58:13)
    at Generator.next (<anonymous>)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    **at /alexblair/windir/www/alexblair_synology_me/test/tinyy/node_modules/.store/append-transform@1.0.0/node_modules/append-transform/index.js:62:4 {
  code: 'ERR_INVALID_ARG_TYPE'
}**

**Node.js v20.6.1
ERROR: "test:unit -- --watch" exited with 1.
2023-09-13 10:55:44 [core-task]: npm run watch 命令执行行失败**** 

tiny  无法启动


### Step to reproduce

**第一步 初始化安装**


**tiny init** 

? 请选择一个适合您项目的套件进行初始化:   dev  ----------  开发tiny-cli套件和插件
? 请选择你想要初始化的模板 tiny套件 ---- 用于生成项目模板
? 输入套件/插件名称(tiny-toolkit-/tiny-plugin- 开头) tiny-toolkit-aa

npminstall WARN load dependencies tree /alexblair/windir/www/alexblair_synology_me/test/tinyy/package-lock.json error: ENOENT: no such file or directory, open '/alexblair/windir/www/alexblair_synology_me/test/tinyy/package-lock.json'
✔ Linked 420 latest versions fallback to /alexblair/windir/www/alexblair_synology_me/test/tinyy/node_modules/.store/node_modules
deprecate @opentiny/cli-devkit@1.1.0 › intl-messageformat@5.4.3 › intl-messageformat-parser@^2.1.3 We've written a new parser that's 6x faster and is backwards compatible. Please use @formatjs/icu-messageformat-parser
deprecate @opentiny/cli-devkit@1.1.0 › mem-fs-editor@6.0.0 › globby@9.2.0 › fast-glob@2.2.7 › micromatch@3.1.10 › snapdragon@0.8.2 › source-map-resolve@^0.5.0 See https://github.com/lydell/source-map-resolve#deprecated
deprecate @opentiny/cli-devkit@1.1.0 › mem-fs-editor@6.0.0 › globby@9.2.0 › fast-glob@2.2.7 › micromatch@3.1.10 › snapdragon@0.8.2 › source-map-resolve@0.5.3 › source-map-url@^0.4.0 See https://github.com/lydell/source-map-url#deprecated
deprecate @opentiny/cli-devkit@1.1.0 › mem-fs-editor@6.0.0 › globby@9.2.0 › fast-glob@2.2.7 › micromatch@3.1.10 › snapdragon@0.8.2 › source-map-resolve@0.5.3 › urix@^0.1.0 Please see https://github.com/lydell/urix#deprecated
deprecate @opentiny/cli-devkit@1.1.0 › mem-fs-editor@6.0.0 › globby@9.2.0 › fast-glob@2.2.7 › micromatch@3.1.10 › snapdragon@0.8.2 › source-map-resolve@0.5.3 › resolve-url@^0.2.1 https://github.com/lydell/resolve-url#deprecated
Recently updated (since 2023-09-06): 4 packages (detail see file /alexblair/windir/www/alexblair_synology_me/test/tinyy/node_modules/.recently_updates.txt)
  Today:
    → @opentiny/cli-devkit@1.1.0 › npminstall@7.10.0 › @npmcli/arborist@6.3.0 › @npmcli/query@^3.0.0(3.0.1) (03:46:53)
  2023-09-12
    → @opentiny/cli-devkit@1.1.0 › winston@3.10.0 › logform@2.5.1 › @types/triple-beam@^1.3.2(1.3.3) (20:54:08)
✔ Run 1 script(s) in 89ms.
✔ Installed 1 packages on /alexblair/windir/www/alexblair_synology_me/test/tinyy
✔ All packages installed (414 packages installed from npm registry, used 4s(network 4s), speed 0B/s, json 0(0B), tarball 0B, manifests cache hit 420, etag hit 0 / miss 0)

dependencies:
+ @opentiny/cli-devkit ^1.1.0

2023-09-13 10:54:48 [tiny-toolkit-dev]: npm 依赖安装成功 

--------------------初始化成功,请按下面提示进行操作--------------------

$ tiny start         # 可一键开启项目开发环境
$ tiny help          # 可查看当前套件的详细帮助

--------------------技术支持：官方小助手微信opentiny-official--------------------




### What is expected

初始化无异常 

**tiny start** 

启动时报错


### What is actually happening


**/alexblair/windir/www/alexblair_synology_me/test/tinyy/node_modules/.store/append-transform@1.0.0/node_modules/append-transform/index.js:1
TypeError [ERR_INVALID_ARG_TYPE]: The "mod" argument must be an instance of Module. Received an instance of Module
    at new NodeError (node:internal/errors:405:5)
    at makeRequireFunction (node:internal/modules/helpers:86:11)
    at Module._compile (node:internal/modules/cjs/loader:1231:19)
    at Module.replacementCompile (/alexblair/windir/www/alexblair_synology_me/test/tinyy/node_modules/.store/append-transform@1.0.0/node_modules/append-transform/index.js:58:13)
    at Generator.next (<anonymous>)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at /alexblair/windir/www/alexblair_synology_me/test/tinyy/node_modules/.store/append-transform@1.0.0/node_modules/append-transform/index.js:62:4 {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v20.6.1
ERROR: "test:unit -- --watch" exited with 1.
2023-09-13 10:55:44 [core-task]: npm run watch 命令执行行失败** 

tiny  无法启动

### Any additional comments (optional)


系统环境 ：
**uname -a**
Linux web-server-ub 5.15.0-83-generic #92-Ubuntu SMP Mon Aug 14 09:30:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**npm -v**
10.1.0

**cnpm -v**
cnpm@9.2.0 (/usr/lib/node_modules/cnpm/lib/parse_argv.js)
npm@9.8.1 (/usr/lib/node_modules/cnpm/node_modules/npm/index.js)
node@20.6.1 (/usr/bin/node)
npminstall@7.10.0 (/usr/lib/node_modules/cnpm/node_modules/npminstall/lib/index.js)
prefix=/usr 
linux x64 5.15.0-83-generic 
registry=https://registry.npmmirror.com

用户权限  1000 （普通用户 因为 TINY 禁止ROOT运行）
安装 TINY时  使用的 SUDO 提权。

### LINKED ISSUE #101: 🐛 [Bug]: springCloud项目 local ces1.0 链接404
### Version

v1.0.1

### node-version

v16.16.0

### Link to minimal reproduction

_No response_

### Step to reproduce

打开 springCloud模板的`cse`指导文件：
https://github.com/opentiny/tiny-cli/blob/dev/packages/toolkits/pro/template/server/springCloud/CSE-ENV_CN.md

打开`ces1.0`链接：https://support.huaweicloud.com/devg-servicestage/ss-devg-0034.html

此链接404

### What is expected

`cse1.0`是一个正确的链接

### What is actually happening

ces1.0是个错误的链接，打开404
https://support.huaweicloud.com/devg-servicestage/ss-devg-0034.html

### Any additional comments (optional)

_No response_

### LINKED ISSUE #102: 🐛 [Bug]: [tiny-toolkit-pro] springCloud项目初始化后开启server环境的命令不正确
### Version

v1.0.1

### node-version

v16.16.0

### Link to minimal reproduction

_No response_

### Step to reproduce

```
tiny init pro
```

```
? 请输入项目名称： vue-spring-cloud
? 请输入项目描述： 基于TinyPro套件创建的中后台系统
* 请选择您希望使用的客户端技术栈： vue
* 请选择您希望使用的服务端技术栈： Spring Cloud
* 请确保已安装数据库服务（参考文档 https://www.opentiny.design/tiny-cli/docs/toolkits/pro#database）：
已完成数据库服务安装，开始配置
* 请选择数据库类型： mySQL
* 请输入数据库地址： 
* 请输入数据库端口： 
* 请输入数据库名称： 
* 请输入登录用户名： 
* 请输入密码： [hidden]
```

```
...

added 1400 packages, and audited 1401 packages in 1m

208 packages are looking for funding
  run `npm fund` for details

21 vulnerabilities (9 moderate, 12 high)

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
2023-09-13 15:42:18 [tiny-toolkit-pro]: 客户端 npm 依赖安装成功

--------------------初始化成功,请按下面提示进行操作--------------------

$ cd vue-spring-cloud/web && npm run start     # 开启web开发环境
$ cd vue-spring-cloud/springCloud && npm run dev    # 开启server开发环境
$ tiny help          # 可查看当前套件的详细帮助

建议将现有初始化的代码提交一次到master分支, 方便后续切换到 daily/x.y.z 分支进行开发

-------------------- 技术支持：官方小助手微信opentiny-official --------------------
```

```
cd vue-spring-cloud/springCloud && npm run dev
```

```
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path D:\OnceSpaces\tiny-test-0913\vue-spring-cloud\springCloud/package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'D:\OnceSpaces\tiny-test-0913\vue-spring-cloud\springCloud\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

### What is expected

开启server开发环境的命令应该正确

### What is actually happening

开启server开发环境的命令不正确，运行报错，原因是 server端没有`package.json`文件

```
cd vue-spring-cloud/springCloud && npm run dev
```

```
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path D:\OnceSpaces\tiny-test-0913\vue-spring-cloud\springCloud/package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'D:\OnceSpaces\tiny-test-0913\vue-spring-cloud\springCloud\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

### Any additional comments (optional)

_No response_

### PR DESCRIPTION
**Pull request by fengyon**
# PR
fix 6 issues:
fix #101 
fix #100 
fix #102 
fix #99 
fix #94 
fix #98 

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our [Commit Message Guidelines](https://github.com/opentiny/tiny-cli/blob/main/CONTRIBUTING.md)
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: packages/toolkits/pro/src/lib/init.ts [hunk 1]
```diff
@@ -316,7 +323,9 @@ export const installDependencies = (answers: ProjectInfo) => {
     console.log(
       chalk.green(
         `${chalk.yellow(
-          `$ cd ${name}/${serverFramework} && npm run dev`
+          serverFramework === ServerFrameworks.SpringCloud
```
Comment (hello-yezi) [inline packages/toolkits/pro/src/lib/init.ts:326]: 这里涉及README_EN.md的修改吗？

Comment (fengyon) [reply packages/toolkits/pro/src/lib/init.ts:326]: 不涉及修改

**Review by h-ivy — APPROVED** [review]
ok
